---
language: python
python: "2.7"
before_install:
install:
 - pip install boto
 - pip install boto3
 - pip install botocore
 - pip install ansible
script:
 - cd tests/
 - ansible-playbook --syntax-check test.yml
 - ansible-playbook -vvv test.yml
